version: "3.9"
services:
  dog-backend:
    build: .
    container_name: dog-backend
    ports:
      - "8000:8000"
    env_file:
      - .env_example
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15
    container_name: database
    env_file:
      - .env_example
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
